### ISSUE TITLE
[CrashManager] Improve BugzillaProvider

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/FuzzManager#642]
The BugzillaProvider lacks a number of features which make its use less attractive than using Bugzilla directly.  

**Tasks**
- [ ] Add summary auto-search to provider, mimicking the behavior of Bugzilla
- [ ] Fix caching bug in template editing
- [ ] Include interface for creating templates as browsable page (dependent on Vueify)
- [ ] Add ability to edit/delete templates (dependent on Vueify)

**Dependencies**
- [ ] #641 [WebUI] Vueify FuzzManager

**Comment by La0** [comment]
Here is a list of improvements we could do:
- simplify the `BugzillaProvider` and `Provider` inheritance, to only keep the bugzilla implementation: this would remove the first field when creating a provider instance (and dynamic import)
- store an encrypted bugzilla API key per user to allow the backend to make authenticated queries on behalf of the user (using [django-cryptography](https://django-cryptography.readthedocs.io/en/latest/))
- add an API endpoint to find similar bugs, and use that in a Vue.js component when creating a bug from crashmanager
- Fix caching bug in template editing
- list all available templates in a new Django page, and make that page discoverable
- vueified template edition, with dynamic validation and faster rendering of lists

**Comment by La0** [comment]
After a discussion with @choller , we cannot store bugzilla API keys in the database, out of security concerns.

In order to make authenticated requests we could store the user's Bugzilla API key on the browser `localStorage`:
- the Bugzilla API key stays on the user computer and is never stored on the server
- a Vue.js form should be added in the user profile to allow him to set/unset the Bugzilla API key stored on the current browser context
- all FuzzManager API endpoints that use the `BugzillaProvider` should support an header `X-Bugzilla-API-Key` sent by the browser.
- only Javascript would easily get access to the token in `localStorage`, so we would really need to convert configuration loading and bug creation to that method (already planned)

**Comment by La0** [comment]
This issue may be closed now @pyoor :smile:

**Comment by pyoor** [comment]
Gladly!
